config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # need devise only for login
  devise_for :users, only: [:sessions]
  resources :credentials do
    get 'show_password', on: :member
    get 'hide_password', on: :member
    get 'fetch_password', on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'credentials#index'
  # resources :users, only: [:create]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(auth_object = nil)
    column_names + _ransackers.keys
  end
end

app/models/credential.rb
class Credential < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # unique and presence true email validation
  validates :email, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # check for authentication before any action
end

app/controllers/credentials_controller.rb
class CredentialsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_credential, only: %i[ show edit update destroy show_password hide_password fetch_password]
  before_action :check_user_role, only: %i[create update destroy]

  # GET /credentials or /credentials.json
  def index
    @credentials = Credential.all
  end

  # GET /credentials/1 or /credentials/1.json
  def show
  end

  def show_password
    render turbo_stream: turbo_stream.update("#{helpers.dom_id(@credential)}_password", partial: "show_password", locals: { credential: @credential })
  end

  def hide_password
    render turbo_stream: turbo_stream.update("#{helpers.dom_id(@credential)}_password", partial: "hide_password", locals: { credential: @credential })
  end

  def fetch_password
    render json: { password: @credential.login_password }
  end

  # GET /credentials/new
  def new
    @credential = Credential.new
    # format.turbo_stream
  end

  # GET /credentials/1/edit
  def edit
  end

  # POST /credentials or /credentials.json
  def create
    params = credential_params.merge({ created_by: current_user.id, updated_by: current_user.id })
    @credential = Credential.new(params)

    respond_to do |format|
      if @credential.save
        format.turbo_stream
        # format.html { redirect_to credential_url(@credential), notice: "Credential was successfully created." }
        # format.json { render :show, status: :created, location: @credential }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credentials/1 or /credentials/1.json
  def update
    params = credential_params.merge(updated_by: current_user.id)
    respond_to do |format|
      if @credential.update(params)
        format.turbo_stream
        # format.html { redirect_to credential_url(@credential), notice: "Credential was successfully updated." }
        # format.json { render :show, status: :ok, location: @credential }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credentials/1 or /credentials/1.json
  def destroy
    @credential.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@credential)}") }
      # format.html { redirect_to credentials_url, notice: "Credential was successfully destroyed." }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credential
      @credential = Credential.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def credential_params
      params.require(:credential).permit(:name, :login_id, :login_password)
    end
  
  def check_user_role
    unless current_user.role == 1
      @error = 'Cant able to perform this opertion'
      redirect_to credentials_path, notice: @error
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credentials_helper.rb
module CredentialsHelper
end

app/views/credentials/_credential.html.erb
<div id="<%= dom_id credential %>">
  <%= turbo_frame_tag (dom_id credential) do %>
    <p>
      <strong>Name:</strong>
      <%= credential.name %>
    </p>

    <p>
      <strong>Login:</strong>
      <%= credential.login_id %>
    </p>

    <p>
      <div style="display: flex; gap: 10px;">
        <strong>Login password: </strong>
        <div id=<%= "#{dom_id credential}_password" %>>
          <%= render 'hide_password', credential: credential %>
        </div>
        <div data-controller="copy-password" data-copy-password-cred-id=<%= credential.id %>>
          <button data-action="click->copy-password#copyValue">Copy</button>
        </div>
      </div>
    </p>

    <p>
      <strong>Created by:</strong>
      <%= User.find_by(id: credential.created_by)&.email %>
    </p>

    <p>
      <strong>Updated by:</strong>
      <%= User.find_by(id: credential.updated_by)&.email %>
    </p>

    <% if current_user.role == 1 %>
      <%= link_to "Edit this credential", edit_credential_path(credential) %>
      <br/><br/>
      <%= button_to "Destroy this credential", credential, method: :delete %>
    <% end %>
  <% end %>
  </br>
</div>

app/views/credentials/_form.html.erb
<%= form_with(model: credential) do |form| %>
  <% if credential.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(credential.errors.count, "error") %> prohibited this credential from being saved:</h2>

      <ul>
        <% credential.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :name, placeholder: 'Name of the application' %>
  </div>

  <div class="mb-3">
    <%= form.text_field :login_id, placeholder: 'Login Id' %>
  </div>

  <div class="mb-3">
    <%= form.text_field :login_password, placeholder: 'Password' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/credentials/_hide_password.html.erb
*****
<%= link_to 'show', show_password_credential_path(credential)%>

app/views/credentials/_new_credential.html.erb
<div>
  <%= turbo_frame_tag 'new-credential' do%>
    <% if current_user.role == 1%>
      <%= link_to "New credential", new_credential_path %>
    <% end %>
  <% end %>
</div>

app/views/credentials/_show_password.html.erb
<%= credential.login_password %>
<%= link_to 'Hide', hide_password_credential_path(credential)%>

app/views/credentials/create.turbo_stream.erb
<%= turbo_stream.append('credentials') do %>
  <% render 'credential', credential: @credential%>
<% end %>

<%= turbo_stream.replace('new-credential') do %>
  <%= render 'new_credential' %>
<% end %>

app/views/credentials/edit.html.erb
<%= turbo_frame_tag (dom_id @credential) do %>

  <%= render "form", credential: @credential %>

  <br>

  <div>
    <%= link_to "Back to credentials", credentials_path %>
  </div>
<% end %>

app/views/credentials/index.html.erb
<%
=begin%>
 <% if notice.present? %>
  <p style="color: green"><%= notice %></p>
<% end %> 
<%
=end%>

<nav class="navbar navbar-expand-lg bg-primary-subtle text-emphasis-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Rently Credentaila Manager</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">About Me</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Log Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link active" %>
        </li>
    </div>
  </div>
</nav>
</br>
<div class="container">
   <%= render 'new_credential' %>
 </br>
</div>

<%
=begin%>
 <%= turbo_frame_tag 'list_all_credentials' do %> 
<%
=end%>
  <div id="credentials" class="container">
    <% @credentials.each do |credential| %>
      <%= render 'credential', credential: credential%>
    <% end %>
    </div>
  </div>
<%
=begin%>
 <% end %> 
<%
=end%>

app/views/credentials/new.html.erb
<%= turbo_frame_tag 'new-credential' do%>
  <h1>New credential</h1>

  <%= render "form", credential: @credential %>

  <br>

  <div>
    <%= link_to "Back to credentials", credentials_path %>
  </div>
<% end %>

app/views/credentials/show.html.erb
<p style="color: green"><%= notice %></p>

Name: <%= @credential.name %>
<br />
Login id: <%= @credential.login_id %>
<br />
Login password: <%= @credential.login_password %>
<br />
Created by: <%= User.find_by(id: @credential.created_by)&.email %>
<br />
Updated by: <%= User.find_by(id: @credential.updated_by)&.email %>
<br />
<br />
<br />
<div>
  <% if current_user.role == 1 %>
    <%= link_to "Edit this credential", edit_credential_path(@credential) %> |
     <%= button_to "Destroy this credential", @credential, method: :delete %>
  <% end %>
  <%= link_to "Back to credentials", credentials_path %>
</div>

app/views/credentials/update.turbo_stream.erb
<%= turbo_stream.replace(dom_id @credential) do %>
  <%= render 'credential', credential: @credential%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentlyCredentialManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>